# Generated by Django 3.0.8 on 2020-07-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0002_auto_20200712_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='click_date',
            field=models.DateField(default='2020-06-06'),
            preserve_default=False,
        ),
    ]
