# Generated by Django 3.0.8 on 2020-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0003_donation_click_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='click_date',
            field=models.DateField(null=True),
        ),
    ]
